name: Push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spellcheck
        uses: crate-ci/typos@master
